### ISSUE TITLE
Only scrolls when finger is touching on IOS

### ISSUE THREAD

**Issue by jon-stayntouch** [iamvijaydev/augment-native-scroll#1]
I cannot scroll with my finger and have it keep going after my finger leaves the screen.

**Comment by iamvijaydev** [comment]
I have fixed and finalized the flavor that can work on both touch and non-touch devices. [Synchronous Scroll Swipe](https://iamvijaydev.github.io/augment-native-scroll/#/synchronous-scroll-swipe)

For more info, please check the latest (v0.6.0) [README](https://github.com/iamvijaydev/augment-native-scroll#augment-native-scroll)

**Comment by sstajduhar** [comment]
Just checked and can verify this behaviour for Synchronous Scroll Swipe

I would suggest that you try adding `-webkit-overflow-scrolling: touch;` and use `scroll` instead of `auto` for overflow, overflow-x or overflo-y to enable momentum scrolling.

It's a bit older article, but I think it's still relevant - https://css-tricks.com/snippets/css/momentum-scrolling-on-ios-overflow-elements/

**Comment by iamvijaydev** [comment]
Hi @jon-stayntouch  

Thank you for your valuable review. The kinetic engine has been re-written. Older experiments has been close. Please check the new [demo here](https://iamvijaydev.github.io/augment-native-scroll/#/synchronous-scroll-swipe)

@sstajduhar: I will add these too.
